version: "3.3"
networks:
  friperie:
    driver: bridge

services:
  # ========================
  # MySQL
  # ========================
  mysql:
    image: mysql:5.7
    container_name: mysql_friperie
    env_file:
      - ./.docker/mysql/mysql.env
    volumes:
      - "./.docker/mysql/storage:/var/lib/mysql"
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks: ["friperie"]

  # ========================
  # Application
  # ========================
  php:
    build: ./.docker/php/
    container_name: php_friperie
    volumes:
      - "./:/var/www/web:cached"
    networks: ["friperie"]

  nginx:
    build: ./.docker/nginx
    container_name: nginx_friperie
    ports:
      - "3200:80"
    depends_on:
      - php
    volumes: ["./:/var/www/web:cached"]
    networks: ["friperie"]

  front:
    image: node:16
    working_dir: /var/www/front
    entrypoint: /var/www/front/entrypoint.sh
    container_name: react_friperie
    ports:
      - "3000:3000"
    depends_on:
      - php
    volumes: ["./front:/var/www/front"]
    networks: ["friperie"]
